package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:58:01 AM by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * Admins generated by hbm2java
 */
public class Admins implements java.io.Serializable {

	private int id;
	private Integer shopId;
	private String name;
	private String username;
	private int phone;
	private String email;
	private Date emailVerifiedAt;
	private String password;
	private String rememberToken;

	public Admins() {
	}

	public Admins(int id, String name, String username, int phone, String email, String password) {
		this.id = id;
		this.name = name;
		this.username = username;
		this.phone = phone;
		this.email = email;
		this.password = password;
	}

	public Admins(int id, Integer shopId, String name, String username, int phone, String email, Date emailVerifiedAt,
			String password, String rememberToken) {
		this.id = id;
		this.shopId = shopId;
		this.name = name;
		this.username = username;
		this.phone = phone;
		this.email = email;
		this.emailVerifiedAt = emailVerifiedAt;
		this.password = password;
		this.rememberToken = rememberToken;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getEmailVerifiedAt() {
		return this.emailVerifiedAt;
	}

	public void setEmailVerifiedAt(Date emailVerifiedAt) {
		this.emailVerifiedAt = emailVerifiedAt;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRememberToken() {
		return this.rememberToken;
	}

	public void setRememberToken(String rememberToken) {
		this.rememberToken = rememberToken;
	}

}
