package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:58:01 AM by Hibernate Tools 3.6.0.Final

/**
 * Brands generated by hbm2java
 */
public class Brands implements java.io.Serializable {

	private int id;
	private String name;

	public Brands() {
	}

	public Brands(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
