package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:58:01 AM by Hibernate Tools 3.6.0.Final

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int id;
	private Integer productTypeId;
	private Integer categoryId;
	private Integer marketId;
	private Integer shopId;
	private Integer countryId;
	private String name;
	private int price;
	private int discountPrice;
	private int discount;
	private int quantity;
	private int views;
	private int likes;
	private int sortOrder;
	private byte status;

	public Products() {
	}

	public Products(int id, String name, int price, int discountPrice, int discount, int quantity, int views, int likes,
			int sortOrder, byte status) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.discountPrice = discountPrice;
		this.discount = discount;
		this.quantity = quantity;
		this.views = views;
		this.likes = likes;
		this.sortOrder = sortOrder;
		this.status = status;
	}

	public Products(int id, Integer productTypeId, Integer categoryId, Integer marketId, Integer shopId,
			Integer countryId, String name, int price, int discountPrice, int discount, int quantity, int views,
			int likes, int sortOrder, byte status) {
		this.id = id;
		this.productTypeId = productTypeId;
		this.categoryId = categoryId;
		this.marketId = marketId;
		this.shopId = shopId;
		this.countryId = countryId;
		this.name = name;
		this.price = price;
		this.discountPrice = discountPrice;
		this.discount = discount;
		this.quantity = quantity;
		this.views = views;
		this.likes = likes;
		this.sortOrder = sortOrder;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(Integer productTypeId) {
		this.productTypeId = productTypeId;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getMarketId() {
		return this.marketId;
	}

	public void setMarketId(Integer marketId) {
		this.marketId = marketId;
	}

	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(int discountPrice) {
		this.discountPrice = discountPrice;
	}

	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
