package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

/**
 * BrandModels generated by hbm2java
 */
public class BrandModels implements java.io.Serializable {

	private int id;
	private ProductTypes productTypes;
	private Brands brands;
	private String name;

	public BrandModels() {
	}

	public BrandModels(int id, ProductTypes productTypes, Brands brands, String name) {
		this.id = id;
		this.productTypes = productTypes;
		this.brands = brands;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductTypes getProductTypes() {
		return this.productTypes;
	}

	public void setProductTypes(ProductTypes productTypes) {
		this.productTypes = productTypes;
	}

	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
