package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private int id;
	private int lft;
	private int rgt;
	private Integer parentId;
	private byte top;
	private int sortOrder;
	private byte status;
	private Set<Products> productses = new HashSet<Products>(0);
	private Set<ProductTypes> productTypeses = new HashSet<ProductTypes>(0);

	public Categories() {
	}

	public Categories(int id, int lft, int rgt, byte top, int sortOrder, byte status) {
		this.id = id;
		this.lft = lft;
		this.rgt = rgt;
		this.top = top;
		this.sortOrder = sortOrder;
		this.status = status;
	}

	public Categories(int id, int lft, int rgt, Integer parentId, byte top, int sortOrder, byte status,
			Set<Products> productses, Set<ProductTypes> productTypeses) {
		this.id = id;
		this.lft = lft;
		this.rgt = rgt;
		this.parentId = parentId;
		this.top = top;
		this.sortOrder = sortOrder;
		this.status = status;
		this.productses = productses;
		this.productTypeses = productTypeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getLft() {
		return this.lft;
	}

	public void setLft(int lft) {
		this.lft = lft;
	}

	public int getRgt() {
		return this.rgt;
	}

	public void setRgt(int rgt) {
		this.rgt = rgt;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public byte getTop() {
		return this.top;
	}

	public void setTop(byte top) {
		this.top = top;
	}

	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

	public Set<ProductTypes> getProductTypeses() {
		return this.productTypeses;
	}

	public void setProductTypeses(Set<ProductTypes> productTypeses) {
		this.productTypeses = productTypeses;
	}

}
