package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:12:18 AM by Hibernate Tools 3.6.0.Final

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private int id;
	private int lft;
	private int rgt;
	private Integer parentId;
	private byte top;
	private int sortOrder;
	private byte status;

	public Categories() {
	}

	public Categories(int id, int lft, int rgt, byte top, int sortOrder, byte status) {
		this.id = id;
		this.lft = lft;
		this.rgt = rgt;
		this.top = top;
		this.sortOrder = sortOrder;
		this.status = status;
	}

	public Categories(int id, int lft, int rgt, Integer parentId, byte top, int sortOrder, byte status) {
		this.id = id;
		this.lft = lft;
		this.rgt = rgt;
		this.parentId = parentId;
		this.top = top;
		this.sortOrder = sortOrder;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getLft() {
		return this.lft;
	}

	public void setLft(int lft) {
		this.lft = lft;
	}

	public int getRgt() {
		return this.rgt;
	}

	public void setRgt(int rgt) {
		this.rgt = rgt;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public byte getTop() {
		return this.top;
	}

	public void setTop(byte top) {
		this.top = top;
	}

	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
