package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Countries generated by hbm2java
 */
public class Countries implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Products> productses = new HashSet<Products>(0);

	public Countries() {
	}

	public Countries(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Countries(int id, String name, Set<Products> productses) {
		this.id = id;
		this.name = name;
		this.productses = productses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
