package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

/**
 * Migrations generated by hbm2java
 */
public class Migrations implements java.io.Serializable {

	private int id;
	private String migration;
	private int batch;

	public Migrations() {
	}

	public Migrations(int id, String migration, int batch) {
		this.id = id;
		this.migration = migration;
		this.batch = batch;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMigration() {
		return this.migration;
	}

	public void setMigration(String migration) {
		this.migration = migration;
	}

	public int getBatch() {
		return this.batch;
	}

	public void setBatch(int batch) {
		this.batch = batch;
	}

}
