package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MOptionValues generated by hbm2java
 */
public class MOptionValues implements java.io.Serializable {

	private int id;
	private MOptions MOptions;
	private Set<ProductTypeMOptions> productTypeMOptionses = new HashSet<ProductTypeMOptions>(0);

	public MOptionValues() {
	}

	public MOptionValues(int id, MOptions MOptions) {
		this.id = id;
		this.MOptions = MOptions;
	}

	public MOptionValues(int id, MOptions MOptions, Set<ProductTypeMOptions> productTypeMOptionses) {
		this.id = id;
		this.MOptions = MOptions;
		this.productTypeMOptionses = productTypeMOptionses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MOptions getMOptions() {
		return this.MOptions;
	}

	public void setMOptions(MOptions MOptions) {
		this.MOptions = MOptions;
	}

	public Set<ProductTypeMOptions> getProductTypeMOptionses() {
		return this.productTypeMOptionses;
	}

	public void setProductTypeMOptionses(Set<ProductTypeMOptions> productTypeMOptionses) {
		this.productTypeMOptionses = productTypeMOptionses;
	}

}
