package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:12:18 AM by Hibernate Tools 3.6.0.Final

/**
 * MOptionValues generated by hbm2java
 */
public class MOptionValues implements java.io.Serializable {

	private int id;
	private Integer MOptionId;

	public MOptionValues() {
	}

	public MOptionValues(int id) {
		this.id = id;
	}

	public MOptionValues(int id, Integer MOptionId) {
		this.id = id;
		this.MOptionId = MOptionId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getMOptionId() {
		return this.MOptionId;
	}

	public void setMOptionId(Integer MOptionId) {
		this.MOptionId = MOptionId;
	}

}
