package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MOptions generated by hbm2java
 */
public class MOptions implements java.io.Serializable {

	private int id;
	private String name;
	private Set<ProductTypeMOptions> productTypeMOptionses = new HashSet<ProductTypeMOptions>(0);
	private Set<MOptionValues> MOptionValueses = new HashSet<MOptionValues>(0);
	private Set<ProductMOptionValues> productMOptionValueses = new HashSet<ProductMOptionValues>(0);

	public MOptions() {
	}

	public MOptions(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public MOptions(int id, String name, Set<ProductTypeMOptions> productTypeMOptionses,
			Set<MOptionValues> MOptionValueses, Set<ProductMOptionValues> productMOptionValueses) {
		this.id = id;
		this.name = name;
		this.productTypeMOptionses = productTypeMOptionses;
		this.MOptionValueses = MOptionValueses;
		this.productMOptionValueses = productMOptionValueses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<ProductTypeMOptions> getProductTypeMOptionses() {
		return this.productTypeMOptionses;
	}

	public void setProductTypeMOptionses(Set<ProductTypeMOptions> productTypeMOptionses) {
		this.productTypeMOptionses = productTypeMOptionses;
	}

	public Set<MOptionValues> getMOptionValueses() {
		return this.MOptionValueses;
	}

	public void setMOptionValueses(Set<MOptionValues> MOptionValueses) {
		this.MOptionValueses = MOptionValueses;
	}

	public Set<ProductMOptionValues> getProductMOptionValueses() {
		return this.productMOptionValueses;
	}

	public void setProductMOptionValueses(Set<ProductMOptionValues> productMOptionValueses) {
		this.productMOptionValueses = productMOptionValueses;
	}

}
