package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:12:18 AM by Hibernate Tools 3.6.0.Final

/**
 * Options generated by hbm2java
 */
public class Options implements java.io.Serializable {

	private int id;
	private Integer productTypeId;
	private String name;

	public Options() {
	}

	public Options(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Options(int id, Integer productTypeId, String name) {
		this.id = id;
		this.productTypeId = productTypeId;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(Integer productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
