package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * OptionValues generated by hbm2java
 */
public class OptionValues implements java.io.Serializable {

	private int id;
	private Options options;
	private Set<ProductOptionValues> productOptionValueses = new HashSet<ProductOptionValues>(0);

	public OptionValues() {
	}

	public OptionValues(int id, Options options) {
		this.id = id;
		this.options = options;
	}

	public OptionValues(int id, Options options, Set<ProductOptionValues> productOptionValueses) {
		this.id = id;
		this.options = options;
		this.productOptionValueses = productOptionValueses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Options getOptions() {
		return this.options;
	}

	public void setOptions(Options options) {
		this.options = options;
	}

	public Set<ProductOptionValues> getProductOptionValueses() {
		return this.productOptionValueses;
	}

	public void setProductOptionValueses(Set<ProductOptionValues> productOptionValueses) {
		this.productOptionValueses = productOptionValueses;
	}

}
