package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

/**
 * PasswordResets generated by hbm2java
 */
public class PasswordResets implements java.io.Serializable {

	private PasswordResetsId id;

	public PasswordResets() {
	}

	public PasswordResets(PasswordResetsId id) {
		this.id = id;
	}

	public PasswordResetsId getId() {
		return this.id;
	}

	public void setId(PasswordResetsId id) {
		this.id = id;
	}

}
