package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int id;
	private ProductTypes productTypes;
	private Markets markets;
	private Countries countries;
	private Categories categories;
	private Shops shops;
	private Integer countryId;
	private String name;
	private int price;
	private int discountPrice;
	private int discount;
	private int quantity;
	private int views;
	private int likes;
	private int sortOrder;
	private byte status;
	private Set<ProductOptionValues> productOptionValueses = new HashSet<ProductOptionValues>(0);

	public Products() {
	}

	public Products(int id, ProductTypes productTypes, Markets markets, Countries countries, Categories categories,
			Shops shops, String name, int price, int discountPrice, int discount, int quantity, int views, int likes,
			int sortOrder, byte status) {
		this.id = id;
		this.productTypes = productTypes;
		this.markets = markets;
		this.countries = countries;
		this.categories = categories;
		this.shops = shops;
		this.name = name;
		this.price = price;
		this.discountPrice = discountPrice;
		this.discount = discount;
		this.quantity = quantity;
		this.views = views;
		this.likes = likes;
		this.sortOrder = sortOrder;
		this.status = status;
	}

	public Products(int id, ProductTypes productTypes, Markets markets, Countries countries, Categories categories,
			Shops shops, Integer countryId, String name, int price, int discountPrice, int discount, int quantity,
			int views, int likes, int sortOrder, byte status, Set<ProductOptionValues> productOptionValueses) {
		this.id = id;
		this.productTypes = productTypes;
		this.markets = markets;
		this.countries = countries;
		this.categories = categories;
		this.shops = shops;
		this.countryId = countryId;
		this.name = name;
		this.price = price;
		this.discountPrice = discountPrice;
		this.discount = discount;
		this.quantity = quantity;
		this.views = views;
		this.likes = likes;
		this.sortOrder = sortOrder;
		this.status = status;
		this.productOptionValueses = productOptionValueses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductTypes getProductTypes() {
		return this.productTypes;
	}

	public void setProductTypes(ProductTypes productTypes) {
		this.productTypes = productTypes;
	}

	public Markets getMarkets() {
		return this.markets;
	}

	public void setMarkets(Markets markets) {
		this.markets = markets;
	}

	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Shops getShops() {
		return this.shops;
	}

	public void setShops(Shops shops) {
		this.shops = shops;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(int discountPrice) {
		this.discountPrice = discountPrice;
	}

	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Set<ProductOptionValues> getProductOptionValueses() {
		return this.productOptionValueses;
	}

	public void setProductOptionValueses(Set<ProductOptionValues> productOptionValueses) {
		this.productOptionValueses = productOptionValueses;
	}

}
