package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

/**
 * ProductTypeMOptions generated by hbm2java
 */
public class ProductTypeMOptions implements java.io.Serializable {

	private int id;
	private MOptionValues MOptionValues;
	private ProductTypes productTypes;
	private MOptions MOptions;

	public ProductTypeMOptions() {
	}

	public ProductTypeMOptions(int id, MOptionValues MOptionValues, ProductTypes productTypes, MOptions MOptions) {
		this.id = id;
		this.MOptionValues = MOptionValues;
		this.productTypes = productTypes;
		this.MOptions = MOptions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MOptionValues getMOptionValues() {
		return this.MOptionValues;
	}

	public void setMOptionValues(MOptionValues MOptionValues) {
		this.MOptionValues = MOptionValues;
	}

	public ProductTypes getProductTypes() {
		return this.productTypes;
	}

	public void setProductTypes(ProductTypes productTypes) {
		this.productTypes = productTypes;
	}

	public MOptions getMOptions() {
		return this.MOptions;
	}

	public void setMOptions(MOptions MOptions) {
		this.MOptions = MOptions;
	}

}
