package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:12:18 AM by Hibernate Tools 3.6.0.Final

/**
 * ProductTypes generated by hbm2java
 */
public class ProductTypes implements java.io.Serializable {

	private int id;
	private Integer categoryId;
	private String name;

	public ProductTypes() {
	}

	public ProductTypes(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public ProductTypes(int id, Integer categoryId, String name) {
		this.id = id;
		this.categoryId = categoryId;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
