package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 2:33:23 PM by Hibernate Tools 3.6.0.Final

/**
 * ProductOptionValues generated by hbm2java
 */
public class ProductOptionValues implements java.io.Serializable {

	private Integer id;
	private OptionValues optionValues;
	private Options options;
	private Products products;

	public ProductOptionValues() {
	}

	public ProductOptionValues(OptionValues optionValues, Options options, Products products) {
		this.optionValues = optionValues;
		this.options = options;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public OptionValues getOptionValues() {
		return this.optionValues;
	}

	public void setOptionValues(OptionValues optionValues) {
		this.optionValues = optionValues;
	}

	public Options getOptions() {
		return this.options;
	}

	public void setOptions(Options options) {
		this.options = options;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

}
