package br.com.uaibusiness.ecommerce.model;
// Generated Nov 24, 2019, 12:12:18 AM by Hibernate Tools 3.6.0.Final

/**
 * Shops generated by hbm2java
 */
public class Shops implements java.io.Serializable {

	private int id;
	private Integer marketId;
	private String name;
	private String address;
	private int productTypesCount;
	private int productsCount;
	private int views;
	private String photo;
	private byte status;

	public Shops() {
	}

	public Shops(int id, String name, String address, int productTypesCount, int productsCount, int views, String photo,
			byte status) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.productTypesCount = productTypesCount;
		this.productsCount = productsCount;
		this.views = views;
		this.photo = photo;
		this.status = status;
	}

	public Shops(int id, Integer marketId, String name, String address, int productTypesCount, int productsCount,
			int views, String photo, byte status) {
		this.id = id;
		this.marketId = marketId;
		this.name = name;
		this.address = address;
		this.productTypesCount = productTypesCount;
		this.productsCount = productsCount;
		this.views = views;
		this.photo = photo;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getMarketId() {
		return this.marketId;
	}

	public void setMarketId(Integer marketId) {
		this.marketId = marketId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getProductTypesCount() {
		return this.productTypesCount;
	}

	public void setProductTypesCount(int productTypesCount) {
		this.productTypesCount = productTypesCount;
	}

	public int getProductsCount() {
		return this.productsCount;
	}

	public void setProductsCount(int productsCount) {
		this.productsCount = productsCount;
	}

	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
